### ISSUE TITLE
Android Studio4.0上面无法生成对应的dimen文件

### ISSUE THREAD

**Issue by alferd0806** [mengzhinan/ScreenMatch#10]

**Comment by W-quan** [comment]
+1  目录倒是生成了

**Comment by BlackCat007** [comment]
+1 都是空目录

**Comment by mengzhinan** [comment]
AS 4.0 可以生成。我这测试的是 Windows，Mac 没测试呢。你们说的是 Mac 上无法生成吗？

**Comment by W-quan** [comment]
是的

**Comment by alferd0806** [comment]
我后面这个问题看了一个回答说是阿里的开发规范那个插件引起的，我试了下把这个插件移除之后就可以正常生成了，不过具体什么原因导致的不清楚

**Comment by taichushouwang** [comment]
> 我后面这个问题看了一个回答说是阿里的开发规范那个插件引起的，我试了下把这个插件移除之后就可以正常生成了，不过具体什么原因导致的不清楚

就是这个原因，我这边是win10，用的AS4.0，把阿里的那个插件Alibaba Java Coding Guidelines，给禁用掉，就可以成功生成文件，如果打开，那就是只生成目录，没有生成文件
