### ISSUE TITLE
Android Studio - 2021.2.1 版本以上生成文件格式异常

### ISSUE THREAD

**Issue by Orange-Jun** [mengzhinan/ScreenMatch#15]
### 升级 Android Studio 版本 后使用插件生成资源文件的格式异常，测试 2021.2.x  版本以上都存在，Android Studio 4.1.1 版本正常
![image](https://user-images.githubusercontent.com/42060663/202141087-25f66b24-123a-426f-87dc-0891e8f1f52d.png)

**Comment by mengzhinan** [comment]
使用 AS 2021.3.1 未复现。
麻烦给你的可复现的 values/dimens.xml 文件发我一份，我这试试。感谢
邮箱：136239173@qq.com

**Comment by mengzhinan** [comment]
复现了，修复中

**Comment by mengzhinan** [comment]
问题已经修复，感谢反馈和支持。
新版本为 3.2，等待 Intellij Plugin 平台审核通过后，即可在 AS 中更新。
