### ISSUE TITLE
请问480*800怎么适配？

### ISSUE THREAD

**Issue by isanwenyu** [mengzhinan/ScreenMatch#3]
你好 480*800匹配那个文件夹？
我试了适配效果好像不理想

**Comment by ak47b51ak47** [comment]
楼上的，请看博主的文章，了解原理和用法：<br/>
http://blog.csdn.net/fesdgasdgasdg/article/details/52325590<br/>
http://blog.csdn.net/fesdgasdgasdg/article/details/78107653<br/>
http://blog.csdn.net/fesdgasdgasdg/article/details/78108169<br/>
http://blog.csdn.net/fesdgasdgasdg/article/details/78133821<br/>

**Comment by isanwenyu** [comment]
拜读了上面的文章 如果我没理解错的话 只是适配了宽度 高度没有适配 
那宽度我还是按照dp标吗 比如1280x720设计图中有个 宽180px 高90px的按钮
我宽标90dp 高标45dp？求教

**Comment by ak47b51ak47** [comment]
for isanwenyu ，我的理解是;
按你上面说的，这个按钮宽高分别给@dimen/dp_90和@dimen/dp_45。设计给1280x720或1920x1080的图为最佳，分别720/2或1080/3即可得到360。其实就是把这两种设计的图完全放进宽度为360dp的范围摆放。高度没有处理，如果超出页面高度，你可以用scrollview控件！！！！不同类型的手机，可能会有底部虚拟键等问题，或实际可用的分辨率不一样(比喻联想A880手机书面分辨率960x540，实际可用分辨率为888x540)，如果设计给960x540的图，你非要完整放进联想A880手机显示，整个内容是不是会高度压缩了？变形了？<br/>
故，非要相别人说的那样，宽高分别给两套dimens值适配，无意义！你控制不了。万一哪天要移到电视上呢？<br/>
如果是关注宽度适配限制，高度正常给@dimen/dp_XXX值，放到任何手机或其他设备上，内容都不会变形挤压，切能正常根据设备的屏幕参数正常放大或缩小。<br/>
如果在某些设备上内容高度超出了设备屏幕范围，只能说是内容太多，用scrollview就可以了。
