### ISSUE TITLE
关于Android studio插件

### ISSUE THREAD

**Issue by liuxvdong031** [mengzhinan/ScreenMatch#4]
请问Android studio插件,默认的values-swXXXdp之外.
我还想生成新的values-sw1080dp的文件夹,请问该如何操作?

**Comment by mengzhinan** [comment]
@liuxvdong031 http://blog.csdn.net/fesdgasdgasdg/article/details/78108169

# 你还有哪些widthDP值需要适配，多个值以英文逗号分隔。如果算出来的widthDP值有小数，取整。比喻411.948，则取411
# 系统默认适配的widthDP值为： 384,392,400,410,411,480,533,592,600,640,662,720,768,800,811,820,960,961,1024,1280,1365
match_dp=

可以参考这个配置参数，如果上面没有你想要的，就加上即可

比喻：match_dp=1080
