### ISSUE TITLE
反馈ScreenMatch BUG

### ISSUE THREAD

**Issue by tcqq** [mengzhinan/ScreenMatch#5]
如果我不添加黄色箭头这段代码
![image](https://user-images.githubusercontent.com/10644057/37941222-b8f5afa0-319f-11e8-8c25-728e3346bf06.png)

生成后的dimens.xml 里面的小数点是逗号
![image](https://user-images.githubusercontent.com/10644057/37941181-74c1e0b0-319f-11e8-9e77-26547f147839.png)

**Comment by mengzhinan** [comment]
刚才仔细阅读了插件的代码，没有生成","逗号的问题。模板文件values/dimens.xml必须是xml格式的文件，即包含xml定义文件头。
