### ISSUE TITLE
反馈ScreenMatch问题

### ISSUE THREAD

**Issue by tcqq** [mengzhinan/ScreenMatch#6]
现在基准dimens的宽度是360，
如果设计图的尺寸是1080x1920，设计图里面有一个View 长度是6px，我应该怎么样才能把6px转换成360对应的dp呢？

**Comment by mengzhinan** [comment]
我的适配原则是：只适配手机宽度；高度如果不规则，就在整个页面外围加个scrollview吧。再说以前16:9，现在18:9，还有屏幕内软按键等，这些大问题没办法规律化。<br/>
那么，现在你有宽度1080px的图，想要放到认为宽度是360dp的手机内，你有6px长度的(随便宽或高)view想把单位转换为360范围内的dp。。。来一个公式:1080px/360dp=6px/Xdp。其实就是把1080/3，如果是720px的图，那就720/2。<br/>
还是上面的1080px的图，拿到里面任意标注px值，/3，得到对应的dp值。<br/>
比喻宽90px高60px的按钮，在程序中就写成宽@dimen/dp_30 高@dimen/dp_20

**Comment by mengzhinan** [comment]
@ dimen/ dp_30 <br/>
@ dimen/ d-_20 <br/>
* 写到一起 被网页屏蔽了

**Comment by tcqq** [comment]
所以1080x1920分辨率下的View高度=6px的情况下，360x640分辨率下的View高度是：6/（1080/360）= 2， 对吗？

**Comment by tcqq** [comment]
我更新了评论，请检查。
