### ISSUE TITLE
部分华为手机适配不起作用

### ISSUE THREAD

**Issue by zzh1026** [mengzhinan/ScreenMatch#8]
我们这边有个华为P9Plus手机, 然后使用dp适配在这个手机上不起作用,测试代码为
`
<TextView
    android:layout_width="180dp"
    android:layout_height="@dimen/dp_20"
    android:layout_marginTop="@dimen/dp_15"
    android:background="#00f" />

<TextView
    android:layout_width="180dp"
    android:layout_height="@dimen/dp_20"
    android:layout_gravity="right"
    android:background="#f0f" />

<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="@dimen/dp_40"
    android:layout_marginTop="@dimen/dp_15"
    android:gravity="center_vertical">

    <TextView
        android:layout_width="@dimen/dp_180"
        android:layout_height="@dimen/dp_30"
        android:background="#f00" />

    <TextView
        android:layout_width="@dimen/dp_180"
        android:layout_height="@dimen/dp_15"
        android:layout_alignParentRight="true"
        android:layout_centerVertical="true"
        android:background="#00f" />

</RelativeLayout>
`
在小米8手机上没问题,但是在华为手机上却表现的完全一致而且完全没有适配, 项目中有sw430dp的适配,结果出来确实默认value中的值,就是说sw适配的时候没起作用,这是怎么回事?请问大神有碰到过吗?

**Comment by mengzhinan** [comment]
没碰到过呢。TextView  width 为 dp_180 也就是屏幕宽度的一半。你需要测试：获取问题手机的总宽度 dp 值，然后看适配的 dimens 文件夹中是否有这个值
